hosts:
  - chargify.local
php: 7.0
machine_name: chargify
extensions:
  - chassis/xdebug
  - chassis/mailhog
  - chassis/fish
  - chassis/sequelpro
  - chassis/tester
  - chassis/composer
  - chassis/phpmyadmin
  - chassis/chassis_openssl
  - chassis/phpcs
  - chassis/pretty_permalinks
composer:
    paths:
        - /vagrant/content/plugins/wp-chargify
    options: --prefer-source --dev
phpunit:
  version: 5.7
hostsupdater: yes
permalink: '/%year%/%monthnum%/%day%/%postname%/'