hosts:
  - chargify.local
php: 7.0
machine_name: chargify
extensions:
  - chassis/xdebug
  - chassis/mailhog
  - chassis/fish
  - chassis/sequelpro
  - chassis/tester
  - chassis/composer
  - chassis/phpmyadmin
  - chassis/chassis_openssl
composer:
    paths:
        - /vagrant/content/plugins/wp-chargify
    options: --prefer-source --dev