/**
 * The states organised by country codes from config-countries.js. Which is organised
 * alphabetically by country name not code.
 *
 * @type { Object }
 * */
export const states = {
	AF: {
		BDS: 'Badakhshan',
		BDG: 'Badghis',
		BGL: 'Baghlan',
		BAL: 'Balkh',
		BAM: 'Bamian',
		DAY: 'Daykondi',
		FRA: 'Farah',
		FYB: 'Faryab',
		GHA: 'Ghazni',
		GHO: 'Ghowr',
		HEL: 'Helmand',
		HER: 'Herat',
		JOW: 'Jowzjan',
		KAB: 'Kabul [Kabol]',
		KAN: 'Kandahar',
		KAP: 'Kapisa',
		KHO: 'Khowst',
		KNR: 'Konar [Kunar]',
		KDZ: 'Kondoz [Kunduz]',
		LAG: 'Laghman',
		LOW: 'Lowgar',
		NAN: 'Nangrahar [Nangarhar]',
		NIM: 'Nimruz',
		NUR: 'Nurestan',
		ORU: 'Oruzgan [Uruzgan]',
		PIA: 'Paktia',
		PKA: 'Paktika',
		PAN: 'Panjshir',
		PAR: 'Parwan',
		SAM: 'Samangan',
		SAR: 'Sar-e Pol',
		TAK: 'Takhar',
		WAR: 'Wardak [Wardag]',
		ZAB: 'Zabol [Zabul]',
	},
	AL: {
		BR: 'Berat',
		BU: 'Bulqizë',
		DL: 'Delvinë',
		DV: 'Devoll',
		DI: 'Dibër',
		DR: 'Durrës',
		EL: 'Elbasan',
		FR: 'Fier',
		GJ: 'Gjirokastër',
		GR: 'Gramsh',
		HA: 'Has',
		KA: 'Kavajë',
		ER: 'Kolonjë',
		KO: 'Korçë',
		KR: 'Krujë',
		KU: 'Kukës',
		KB: 'Kurbin',
		KC: 'Kuçovë',
		LE: 'Lezhë',
		LB: 'Librazhd',
		LU: 'Lushnjë',
		MK: 'Mallakastër',
		MM: 'Malësi e Madhe',
		MT: 'Mat',
		MR: 'Mirditë',
		PQ: 'Peqin',
		PG: 'Pogradec',
		PU: 'Pukë',
		PR: 'Përmet',
		SR: 'Sarandë',
		SH: 'Shkodër',
		SK: 'Skrapar',
		TE: 'Tepelenë',
		TR: 'Tiranë',
		TP: 'Tropojë',
		VL: 'Vlorë',
	},
	DZ: {
		'01': 'Adrar',
		'16': 'Alger',
		'23': 'Annaba',
		'44': 'Aïn Defla',
		'46': 'Aïn Témouchent',
		'05': 'Batna',
		'07': 'Biskra',
		'09': 'Blida',
		'34': 'Bordj Bou Arréridj',
		'10': 'Bouira',
		'35': 'Boumerdès',
		'08': 'Béchar',
		'06': 'Béjaïa',
		'02': 'Chlef',
		'25': 'Constantine',
		'17': 'Djelfa',
		'32': 'El Bayadh',
		'39': 'El Oued',
		'36': 'El Tarf',
		'47': 'Ghardaïa',
		'24': 'Guelma',
		'33': 'Illizi',
		'18': 'Jijel',
		'40': 'Khenchela',
		'03': 'Laghouat',
		'29': 'Mascara',
		'43': 'Mila',
		'27': 'Mostaganem',
		'28': 'Msila',
		'26': 'Médéa',
		'45': 'Naama',
		'31': 'Oran',
		'30': 'Ouargla',
		'04': 'Oum el Bouaghi',
		'48': 'Relizane',
		'20': 'Saïda',
		'22': 'Sidi Bel Abbès',
		'21': 'Skikda',
		'41': 'Souk Ahras',
		'19': 'Sétif',
		'11': 'Tamanghasset',
		'14': 'Tiaret',
		'37': 'Tindouf',
		'42': 'Tipaza',
		'38': 'Tissemsilt',
		'15': 'Tizi Ouzou',
		'13': 'Tlemcen',
		'12': 'Tébessa',
	},
	AS: {},
	AD: {
		'07': 'Andorra la Vella',
		'02': 'Canillo',
		'03': 'Encamp',
		'08': 'Escaldes-Engordany',
		'04': 'La Massana',
		'05': 'Ordino',
		'06': 'Sant Julià de Lòria',
	},
	AO: {
		BGO: 'Bengo',
		BGU: 'Benguela',
		BIE: 'Bié',
		CAB: 'Cabinda',
		CCU: 'Cuando-Cubango',
		CNO: 'Cuanza Norte',
		CUS: 'Cuanza Sul',
		CNN: 'Cunene',
		HUA: 'Huambo',
		HUI: 'Huíla',
		LUA: 'Luanda',
		LNO: 'Lunda Norte',
		LSU: 'Lunda Sul',
		MAL: 'Malange',
		MOX: 'Moxico',
		NAM: 'Namibe',
		UIG: 'Uíge',
		ZAI: 'Zaire',
	},
	AI: {},
	AQ: {},
	AG: {
		'10': 'Barbuda',
		'X2~': 'Redonda',
		'03': 'Saint George',
		'04': 'Saint John’s',
		'05': 'Saint Mary',
		'06': 'Saint Paul',
		'07': 'Saint Peter',
		'08': 'Saint Philip',
	},
	AR: {
		B: 'Buenos Aires',
		C: 'Capital federal',
		K: 'Catamarca',
		H: 'Chaco',
		U: 'Chubut',
		W: 'Corrientes',
		X: 'Córdoba',
		E: 'Entre Ríos',
		P: 'Formosa',
		Y: 'Jujuy',
		L: 'La Pampa',
		F: 'La Rioja',
		M: 'Mendoza',
		N: 'Misiones',
		Q: 'Neuquén',
		R: 'Río Negro',
		A: 'Salta',
		J: 'San Juan',
		D: 'San Luis',
		Z: 'Santa Cruz',
		S: 'Santa Fe',
		G: 'Santiago del Estero',
		V: 'Tierra del Fuego',
		T: 'Tucumán',
	},
	AM: {
		AG: 'Aragac?otn',
		AR: 'Ararat',
		AV: 'Armavir',
		ER: 'Erevan',
		GR: 'Gegarkunik\'',
		KT: 'Kotayk\'',
		LO: 'Lo?y',
		SU: 'Syunik\'',
		TV: 'Tavuš',
		VD: 'Vayoc Jor',
		SH: 'Širak',
	},
	AW: {},
	AU: {
		ACT: 'Australian Capital Territory',
		NSW: 'New South Wales',
		NT: 'Northern Territory',
		QLD: 'Queensland',
		SA: 'South Australia',
		TAS: 'Tasmania',
		VIC: 'Victoria',
		WA: 'Western Australia',
	},
	AT: {
		'1': 'Burgenland',
		'2': 'Kärnten',
		'3': 'Niederösterreich',
		'4': 'Oberösterreich',
		'5': 'Salzburg',
		'6': 'Steiermark',
		'7': 'Tirol',
		'8': 'Vorarlberg',
		'9': 'Wien',
	},
	AZ: {
		ABS: 'Abseron',
		AGC: 'Agcabädi',
		AGM: 'Agdam',
		AGS: 'Agdas',
		AGA: 'Agstafa',
		AGU: 'Agsu',
		AST: 'Astara',
		BAB: 'Babäk',
		BA: 'Baki',
		BAL: 'Balakän',
		BEY: 'Beyläqan',
		BIL: 'Biläsuvar',
		BAR: 'Bärdä',
		CUL: 'Culfa',
		CAB: 'Cäbrayil',
		CAL: 'Cälilabab',
		DAS: 'Daskäsän',
		DAV: 'Däväçi',
		FUZ: 'Füzuli',
		GOR: 'Goranboy',
		GAD: 'Gädäbäy',
		GA: 'Gäncä',
		GOY: 'Göyçay',
		HAC: 'Haciqabul',
		IMI: 'Imisli',
		ISM: 'Ismayilli',
		KAL: 'Kälbäcär',
		KUR: 'Kürdämir',
		LAC: 'Laçin',
		LER: 'Lerik',
		LAN: 'Länkäran',
		LA: 'Länkäran City',
		MAS: 'Masalli',
		MI: 'Mingäçevir',
		NA: 'Naftalan',
		NX: 'Naxçivan',
		NEF: 'Neftçala',
		OGU: 'Oguz',
		ORD: 'Ordubad',
		QAX: 'Qax',
		QAZ: 'Qazax',
		QOB: 'Qobustan',
		QBA: 'Quba',
		QBI: 'Qubadli',
		QUS: 'Qusar',
		QAB: 'Qäbälä',
		SAT: 'Saatli',
		SAB: 'Sabirabad',
		SAH: 'Sahbuz',
		SAL: 'Salyan',
		SMI: 'Samaxi',
		SMX: 'Samux',
		SIY: 'Siyäzän',
		SM: 'Sumqayit',
		SUS: 'Susa',
		SS: 'Susa City',
		SAD: 'Sädäräk',
		SAK: 'Säki',
		SA: 'Säki City',
		SKR: 'Sämkir',
		SAR: 'Särur',
		TOV: 'Tovuz',
		TAR: 'Tärtär',
		UCA: 'Ucar',
		XA: 'Xankändi',
		XAN: 'Xanlar',
		XAC: 'Xaçmaz',
		XIZ: 'Xizi',
		XCI: 'Xocali',
		XVD: 'Xocavänd',
		YAR: 'Yardimli',
		YEV: 'Yevlax',
		YE: 'Yevlax City',
		ZAQ: 'Zaqatala',
		ZAN: 'Zängilan',
		ZAR: 'Zärdab',
		AB: 'Äli Bayramli',
	},
	BS: {
		AC: 'Acklins and Crooked Islands',
		BI: 'Bimini',
		CI: 'Cat Island',
		EX: 'Exuma',
		FP: 'Freeport',
		FC: 'Fresh Creek',
		GH: 'Governor\'s Harbour',
		GT: 'Green Turtle Cay',
		HI: 'Harbour Island',
		HR: 'High Rock',
		IN: 'Inagua',
		KB: 'Kemps Bay',
		LI: 'Long Island',
		MH: 'Marsh Harbour',
		MG: 'Mayaguana',
		NP: 'New Providence',
		NB: 'Nicholls Town and Berry Islands',
		RI: 'Ragged Island',
		RS: 'Rock Sound',
		SR: 'San Salvador and Rum Cay',
		SP: 'Sandy Point',
	},
	BH: {
		'14': 'Al Janubiyah',
		'13': 'Al Manamah (Al ‘Asimah)',
		'15': 'Al Muharraq',
		'16': 'Al Wustá',
		'17': 'Ash Shamaliyah',
	},
	BD: {
		'05': 'Bagerhat zila',
		'01': 'Bandarban zila',
		'02': 'Barguna zila',
		'06': 'Barisal zila',
		'07': 'Bhola zila',
		'03': 'Bogra zila',
		'04': 'Brahmanbaria zila',
		'09': 'Chandpur zila',
		'10': 'Chittagong zila',
		'12': 'Chuadanga zila',
		'08': 'Comilla zila',
		'11': 'Cox\'s Bazar zila',
		'13': 'Dhaka zila',
		'14': 'Dinajpur zila',
		'15': 'Faridpur zila',
		'16': 'Feni zila',
		'19': 'Gaibandha zila',
		'18': 'Gazipur zila',
		'17': 'Gopalganj zila',
		'20': 'Habiganj zila',
		'24': 'Jaipurhat zila',
		'21': 'Jamalpur zila',
		'22': 'Jessore zila',
		'25': 'Jhalakati zila',
		'23': 'Jhenaidah zila',
		'29': 'Khagrachari zila',
		'27': 'Khulna zila',
		'26': 'Kishoreganj zila',
		'28': 'Kurigram zila',
		'30': 'Kushtia zila',
		'31': 'Lakshmipur zila',
		'32': 'Lalmonirhat zila',
		'36': 'Madaripur zila',
		'37': 'Magura zila',
		'33': 'Manikganj zila',
		'39': 'Meherpur zila',
		'38': 'Moulvibazar zila',
		'35': 'Munshiganj zila',
		'34': 'Mymensingh zila',
		'48': 'Naogaon zila',
		'43': 'Narail zila',
		'40': 'Narayanganj zila',
		'42': 'Narsingdi zila',
		'44': 'Natore zila',
		'45': 'Nawabganj zila',
		'41': 'Netrakona zila',
		'46': 'Nilphamari zila',
		'47': 'Noakhali zila',
		'49': 'Pabna zila',
		'52': 'Panchagarh zila',
		'51': 'Patuakhali zila',
		'50': 'Pirojpur zila',
		'53': 'Rajbari zila',
		'54': 'Rajshahi zila',
		'56': 'Rangamati zila',
		'55': 'Rangpur zila',
		'58': 'Satkhira zila',
		'62': 'Shariatpur zila',
		'57': 'Sherpur zila',
		'59': 'Sirajganj zila',
		'61': 'Sunamganj zila',
		'60': 'Sylhet zila',
		'63': 'Tangail zila',
		'64': 'Thakurgaon zila',
	},
	BB: {
		'01': 'Christ Church',
		'02': 'Saint Andrew',
		'03': 'Saint George',
		'04': 'Saint James',
		'05': 'Saint John',
		'06': 'Saint Joseph',
		'07': 'Saint Lucy',
		'08': 'Saint Michael',
		'09': 'Saint Peter',
		'10': 'Saint Philip',
		'11': 'Saint Thomas',
	},
	BY: {
		BR: 'Brestskaya voblasts\' (be) Brestskaya oblast\' (ru)',
		HO: 'Homyel\'skaya voblasts\' (be) Gomel\'skaya oblast\' (ru)',
		'X1~': 'Horad Minsk',
		HR: 'Hrodzenskaya voblasts\' (be) Grodnenskaya oblast\' (ru)',
		MA: 'Mahilyowskaya voblasts\' (be) Mogilevskaya oblast\' (ru)',
		MI: 'Minskaya voblasts\' (be) Minskaya oblast\' (ru)',
		VI: 'Vitsyebskaya voblasts\' (be) Vitebskaya oblast\' (ru)',
	},
	BE: {
		VAN: 'Antwerpen (nl)',
		WBR: 'Brabant Wallon (fr)',
		BRU: 'Brussels',
		WHT: 'Hainaut (fr)',
		VLI: 'Limburg (nl)',
		WLG: 'Liège (fr)',
		WLX: 'Luxembourg (fr)',
		WNA: 'Namur (fr)',
		VOV: 'Oost-Vlaanderen (nl)',
		VBR: 'Vlaams Brabant (nl)',
		VWV: 'West-Vlaanderen (nl)',
	},
	BZ: {
		BZ: 'Belize',
		CY: 'Cayo',
		CZL: 'Corozal',
		OW: 'Orange Walk',
		SC: 'Stann Creek',
		TOL: 'Toledo',
	},
	BJ: {
		AL: 'Alibori',
		AK: 'Atakora',
		AQ: 'Atlantique',
		BO: 'Borgou',
		CO: 'Collines',
		DO: 'Donga',
		KO: 'Kouffo',
		LI: 'Littoral',
		MO: 'Mono',
		OU: 'Ouémé',
		PL: 'Plateau',
		ZO: 'Zou',
	},
	BM: {},
	BT: {
		'33': 'Bumthang',
		'12': 'Chhukha',
		'22': 'Dagana',
		'GA': 'Gasa',
		'13': 'Ha',
		'44': 'Lhuentse',
		'42': 'Monggar',
		'11': 'Paro',
		'43': 'Pemagatshel',
		'23': 'Punakha',
		'45': 'Samdrup Jongkha',
		'14': 'Samtse',
		'31': 'Sarpang',
		'15': 'Thimphu',
		'TY': 'Trashi Yangtse',
		'41': 'Trashigang',
		'32': 'Trongsa',
		'21': 'Tsirang',
		'24': 'Wangdue Phodrang',
		'34': 'Zhemgang',
	},
	BO: {
		H: 'Chuquisaca',
		C: 'Cochabamba',
		B: 'El Beni',
		L: 'La Paz',
		O: 'Oruro',
		N: 'Pando',
		P: 'Potosí',
		S: 'Santa Cruz',
		T: 'Tarija',
	},
	BQ: {
		BO: 'Bonaire',
		SA: 'Saba',
		SE: 'Sint Eustatius',
	},
	BA: {
		BIH: 'Federacija Bosna i Hercegovina',
		SRP: 'Republika Srpska',
	},
	BW: {
		CE: 'Central',
		GH: 'Ghanzi',
		KG: 'Kgalagadi',
		KL: 'Kgatleng',
		KW: 'Kweneng',
		NE: 'North-East',
		NW: 'North-West',
		SE: 'South-East',
		SO: 'Southern',
	},
	BV: {},
	BR: {
		AC: 'Acre',
		AL: 'Alagoas',
		AP: 'Amapá',
		AM: 'Amazonas',
		BA: 'Bahia',
		CE: 'Ceará',
		DF: 'Distrito Federal',
		ES: 'Espírito Santo',
		GO: 'Goiás',
		MA: 'Maranhão',
		MT: 'Mato Grosso',
		MS: 'Mato Grosso do Sul',
		MG: 'Minas Gerais',
		PR: 'Paraná',
		PB: 'Paraíba',
		PA: 'Pará',
		PE: 'Pernambuco',
		PI: 'Piauí',
		RN: 'Rio Grande do Norte',
		RS: 'Rio Grande do Sul',
		RJ: 'Rio de Janeiro',
		RO: 'Rondônia',
		RR: 'Roraima',
		SC: 'Santa Catarina',
		SE: 'Sergipe',
		SP: 'São Paulo',
		TO: 'Tocantins',
	},
	IO: {},
	BN: {
		BE: 'Belait',
		BM: 'Brunei-Muara',
		TE: 'Temburong',
		TU: 'Tutong',
	},
	BG: {
		'01': 'Blagoevgrad',
		'02': 'Burgas',
		'08': 'Dobrich',
		'07': 'Gabrovo',
		'26': 'Haskovo',
		'09': 'Kardzhali',
		'10': 'Kjustendil',
		'11': 'Lovech',
		'12': 'Montana',
		'13': 'Pazardzhik',
		'14': 'Pernik',
		'15': 'Pleven',
		'16': 'Plovdiv',
		'17': 'Razgrad',
		'18': 'Ruse',
		'19': 'Silistra',
		'20': 'Sliven',
		'21': 'Smolyan',
		'23': 'Sofia',
		'22': 'Sofia-Grad',
		'24': 'Stara Zagora',
		'25': 'Targovishte',
		'03': 'Varna',
		'04': 'Veliko Tarnovo',
		'05': 'Vidin',
		'06': 'Vratsa',
		'28': 'Yambol',
		'27': 'Šumen',
	},
	BF: {
		BAL: 'Balé',
		BAM: 'Bam',
		BAN: 'Banwa',
		BAZ: 'Bazèga',
		BGR: 'Bougouriba',
		BLG: 'Boulgou',
		BLK: 'Boulkiemdé',
		COM: 'Comoé',
		GAN: 'Ganzourgou',
		GNA: 'Gnagna',
		GOU: 'Gourma',
		HOU: 'Houet',
		IOB: 'Ioba',
		KAD: 'Kadiogo',
		KMD: 'Komondjari',
		KMP: 'Kompienga',
		KOS: 'Kossi',
		KOP: 'Koulpélogo',
		KOT: 'Kouritenga',
		KOW: 'Kourwéogo',
		KEN: 'Kénédougou',
		LOR: 'Loroum',
		LER: 'Léraba',
		MOU: 'Mouhoun',
		NAO: 'Nahouri',
		NAM: 'Namentenga',
		NAY: 'Nayala',
		NOU: 'Noumbiel',
		OUB: 'Oubritenga',
		OUD: 'Oudalan',
		PAS: 'Passoré',
		PON: 'Poni',
		SNG: 'Sanguié',
		SMT: 'Sanmatenga',
		SIS: 'Sissili',
		SOM: 'Soum',
		SOR: 'Sourou',
		SEN: 'Séno',
		TAP: 'Tapoa',
		TUI: 'Tui',
		YAG: 'Yagha',
		YAT: 'Yatenga',
		ZIR: 'Ziro',
		ZON: 'Zondoma',
		ZOU: 'Zoundwéogo',
	},
	BI: {
		BB: 'Bubanza',
		BJ: 'Bujumbura',
		BR: 'Bururi',
		CA: 'Cankuzo',
		CI: 'Cibitoke',
		GI: 'Gitega',
		KR: 'Karuzi',
		KY: 'Kayanza',
		KI: 'Kirundo',
		MA: 'Makamba',
		MU: 'Muramvya',
		MY: 'Muyinga',
		MW: 'Mwaro',
		NG: 'Ngozi',
		RT: 'Rutana',
		RY: 'Ruyigi',
	},
	KH: {
		'2': 'Baat Dambang [Batdâmbâng]',
		'1': 'Banteay Mean Chey [Bântéay Méanchey]',
		'3': 'Kampong Chaam [Kâmpóng Cham]',
		'4': 'Kampong Chhnang [Kâmpóng Chhnang]',
		'5': 'Kampong Spueu [Kâmpóng Spœ]',
		'6': 'Kampong Thum [Kâmpóng Thum]',
		'7': 'Kampot [Kâmpôt]',
		'8': 'Kandaal [Kândal]',
		'9': 'Kaoh Kong [Kaôh Kong]',
		'10': 'Kracheh [Krâchéh]',
		'23': 'Krong Kep [Krong Kêb]',
		'24': 'Krong Pailin [Krong Pailin]',
		'18': 'Krong Preah Sihanouk [Krong Preah Sihanouk]',
		'11': 'Mondol Kiri [Môndól Kiri]',
		'22': 'Otdar Mean Chey [Otdâr Méanchey]',
		'12': 'Phnom Penh [Phnum Pénh]',
		'15': 'Pousaat [Pouthisat]',
		'13': 'Preah Vihear [Preah Vihéar]',
		'14': 'Prey Veaeng [Prey Vêng]',
		'16': 'Rotanak Kiri [Rôtânôkiri]',
		'17': 'Siem Reab [Siemréab]',
		'19': 'Stueng Traeng [Stœ?ng Trêng]',
		'20': 'Svaay Rieng [Svay Rieng]',
		'21': 'Taakaev [Takêv]',
	},
	CM: {
		AD: 'Adamaoua',
		CE: 'Centre',
		ES: 'East',
		EN: 'Far North',
		LT: 'Littoral',
		NO: 'North',
		NW: 'North-West',
		SU: 'South',
		SW: 'South-West',
		OU: 'West',
	},
	CA: {
		AB: 'Alberta',
		BC: 'British Columbia',
		MB: 'Manitoba',
		NB: 'New Brunswick',
		NL: 'Newfoundland and Labrador',
		NT: 'Northwest Territories',
		NS: 'Nova Scotia',
		NU: 'Nunavut',
		ON: 'Ontario',
		PE: 'Prince Edward Island',
		QC: 'Quebec',
		SK: 'Saskatchewan',
		YT: 'Yukon Territory',
	},
	IC: {},
	CV: {
		BV: 'Boa Vista',
		BR: 'Brava',
		CS: 'Calheta de São Miguel',
		MA: 'Maio',
		MO: 'Mosteiros',
		PA: 'Paúl',
		PN: 'Porto Novo',
		PR: 'Praia',
		RG: 'Ribeira Grande',
		SL: 'Sal',
		CA: 'Santa Catarina',
		CR: 'Santa Cruz',
		SD: 'São Domingos',
		SF: 'São Filipe',
		SN: 'São Nicolau',
		SV: 'São Vicente',
		TA: 'Tarrafal',
	},
	KY: {},
	CF: {
		BB: 'Bamingui-Bangoran',
		BGF: 'Bangui',
		BK: 'Basse-Kotto',
		HM: 'Haut-Mbomou',
		HK: 'Haute-Kotto',
		KG: 'Kémo',
		LB: 'Lobaye',
		HS: 'Mambéré-Kadéï',
		MB: 'Mbomou',
		KB: 'Nana-Grébizi',
		NM: 'Nana-Mambéré',
		MP: 'Ombella-Mpoko',
		UK: 'Ouaka',
		AC: 'Ouham',
		OP: 'Ouham-Pendé',
		SE: 'Sangha-Mbaéré',
		VK: 'Vakaga',
	},
	TD: {
		BA: 'Batha',
		BET: 'Borkou-Ennedi-Tibesti',
		CB: 'Chari-Baguirmi',
		GR: 'Guéra',
		HL: 'Hadjer Lamis',
		KA: 'Kanem',
		LC: 'Lac',
		LO: 'Logone-Occidental',
		LR: 'Logone-Oriental',
		MA: 'Mandoul',
		ME: 'Mayo-Kébbi-Est',
		MO: 'Mayo-Kébbi-Ouest',
		MC: 'Moyen-Chari',
		ND: 'Ndjamena',
		OD: 'Ouaddaï',
		SA: 'Salamat',
		TA: 'Tandjilé',
		WF: 'Wadi Fira',
	},
	CL: {
		AI: 'Aisén del General Carlos Ibáñez del Campo',
		AN: 'Antofagasta',
		AR: 'Araucanía',
		AP: 'Arica y Parinacota',
		AT: 'Atacama',
		BI: 'Bío-Bío',
		CO: 'Coquimbo',
		LI: 'Libertador General Bernardo O\'Higgins',
		LL: 'Los Lagos',
		LR: 'Los Ríos',
		MA: 'Magallanes',
		ML: 'Maule',
		RM: 'Región Metropolitana de Santiago',
		TA: 'Tarapacá',
		VS: 'Valparaíso',
	},
	CN: {
		'34': 'Anhui',
		'92': 'Aomen (zh) ***',
		'11': 'Beijing',
		'50': 'Chongqing',
		'35': 'Fujian',
		'62': 'Gansu',
		'44': 'Guangdong',
		'45': 'Guangxi',
		'52': 'Guizhou',
		'46': 'Hainan',
		'13': 'Hebei',
		'23': 'Heilongjiang',
		'41': 'Henan',
		'42': 'Hubei',
		'43': 'Hunan',
		'32': 'Jiangsu',
		'36': 'Jiangxi',
		'22': 'Jilin',
		'21': 'Liaoning',
		'15': 'Nei Mongol (mn)',
		'64': 'Ningxia',
		'63': 'Qinghai',
		'61': 'Shaanxi',
		'37': 'Shandong',
		'31': 'Shanghai',
		'14': 'Shanxi',
		'51': 'Sichuan',
		'71': 'Taiwan *',
		'12': 'Tianjin',
		'91': 'Xianggang (zh) **',
		'65': 'Xinjiang',
		'54': 'Xizang',
		'53': 'Yunnan',
		'33': 'Zhejiang',
	},
	CX: {},
	CC: {},
	CO: {
		AMA: 'Amazonas',
		ANT: 'Antioquia',
		ARA: 'Arauca',
		ATL: 'Atlántico',
		BOL: 'Bolívar',
		BOY: 'Boyacá',
		CAL: 'Caldas',
		CAQ: 'Caquetá',
		CAS: 'Casanare',
		CAU: 'Cauca',
		CES: 'Cesar',
		CHO: 'Chocó',
		CUN: 'Cundinamarca',
		COR: 'Córdoba',
		DC: 'Distrito Capital de Bogotá',
		GUA: 'Guainía',
		GUV: 'Guaviare',
		HUI: 'Huila',
		LAG: 'La Guajira',
		MAG: 'Magdalena',
		MET: 'Meta',
		NAR: 'Nariño',
		NSA: 'Norte de Santander',
		PUT: 'Putumayo',
		QUI: 'Quindío',
		RIS: 'Risaralda',
		SAP: 'San Andrés, Providencia y Santa Catalina',
		SAN: 'Santander',
		SUC: 'Sucre',
		TOL: 'Tolima',
		VAC: 'Valle del Cauca',
		VAU: 'Vaupés',
		VID: 'Vichada',
	},
	KM: {
		A: 'Anjouan',
		G: 'Grande Comore',
		M: 'Mohéli',
	},
	CG: {
		'11': 'Bouenza',
		'BZV': 'Brazzaville',
		'8': 'Cuvette',
		'15': 'Cuvette-Ouest',
		'5': 'Kouilou',
		'7': 'Likouala',
		'2': 'Lékoumou',
		'9': 'Niari',
		'14': 'Plateaux',
		'12': 'Pool',
		'13': 'Sangha',
	},
	CD: {
		BN: 'Bandundu',
		BC: 'Bas-Congo',
		KW: 'Kasai-Occidental',
		KE: 'Kasai-Oriental',
		KA: 'Katanga',
		KN: 'Kinshasa',
		MA: 'Maniema',
		NK: 'Nord-Kivu',
		OR: 'Orientale',
		SK: 'Sud-Kivu',
		EQ: 'Équateur',
	},
	CK: {},
	CR: {
		A: 'Alajuela',
		C: 'Cartago',
		G: 'Guanacaste',
		H: 'Heredia',
		L: 'Limón',
		P: 'Puntarenas',
		SJ: 'San José',
	},
	HR: {
		'07': 'Bjelovarsko-bilogorska županija',
		'12': 'Brodsko-posavska županija',
		'19': 'Dubrovačko-neretvanska županija',
		'21': 'Grad Zagreb',
		'18': 'Istarska županija',
		'04': 'Karlovačka županija',
		'06': 'Koprivničko-križevačka županija',
		'02': 'Krapinsko-zagorska županija',
		'09': 'Ličko-senjska županija',
		'20': 'Međimurska županija',
		'14': 'Osječko-baranjska županija',
		'11': 'Požeško-slavonska županija',
		'08': 'Primorsko-goranska županija',
		'03': 'Sisačko-moslavačka županija',
		'17': 'Splitsko-dalmatinska županija',
		'05': 'Varaždinska županija',
		'10': 'Virovitičko-podravska županija',
		'16': 'Vukovarsko-srijemska županija',
		'13': 'Zadarska županija',
		'01': 'Zagrebačka županija',
		'15': 'Šibensko-kninska županija',
	},
	CU: {
		'09': 'Camagüey',
		'08': 'Ciego de Ávila',
		'06': 'Cienfuegos',
		'03': 'Ciudad de La Habana',
		'12': 'Granma',
		'14': 'Guantánamo',
		'11': 'Holguín',
		'99': 'Isla de la Juventud',
		'02': 'La Habana',
		'10': 'Las Tunas',
		'04': 'Matanzas',
		'01': 'Pinar del Río',
		'07': 'Sancti Spíritus',
		'13': 'Santiago de Cuba',
		'05': 'Villa Clara',
	},
	CW: {},
	CY: {
		'04': 'Ammochostos',
		'06': 'Keryneia',
		'03': 'Larnaka',
		'01': 'Lefkosia',
		'02': 'Lemesos',
		'05': 'Pafos',
	},
	CZ: {
		JC: 'Jihoceský kraj',
		JM: 'Jihomoravský kraj',
		KA: 'Karlovarský kraj',
		KR: 'Královéhradecký kraj',
		LI: 'Liberecký kraj',
		MO: 'Moravskoslezský kraj',
		OL: 'Olomoucký kraj',
		PA: 'Pardubický kraj',
		PL: 'Plzenský kraj',
		PR: 'Praha, hlavní mesto',
		ST: 'Stredoceský kraj',
		VY: 'Vysocina',
		ZL: 'Zlínský kraj',
		US: 'Ústecký kraj',
	},
	CI: {
		'06': '18 Montagnes (Région des)',
		'16': 'Agnébi (Région de l\')',
		'17': 'Bafing (Région du)',
		'09': 'Bas-Sassandra (Région du)',
		'10': 'Denguélé (Région du)',
		'18': 'Fromager (Région du)',
		'02': 'Haut-Sassandra (Région du)',
		'07': 'Lacs (Région des)',
		'01': 'Lagunes (Région des)',
		'12': 'Marahoué (Région de la)',
		'19': 'Moyen-Cavally (Région du)',
		'05': 'Moyen-Comoé (Région du)',
		'11': 'Nzi-Comoé (Région)',
		'03': 'Savanes (Région des)',
		'15': 'Sud-Bandama (Région du)',
		'13': 'Sud-Comoé (Région du)',
		'04': 'Vallée du Bandama (Région de la)',
		'14': 'Worodougou (Région du)',
		'08': 'Zanzan (Région du)',
	},
	DK: {
		'84': 'Capital Region of Denmark',
		'82': 'Central Denmark Region',
		'81': 'North Denmark Region',
		'85': 'Region Zealand',
		'83': 'Region of Southern Denmark',
	},
	DJ: {
		AS: 'Ali Sabieh',
		AR: 'Arta',
		DI: 'Dikhil',
		DJ: 'Djibouti',
		OB: 'Obock',
		TA: 'Tadjourah',
	},
	DM: {
		'02': 'Saint Andrew',
		'03': 'Saint David',
		'04': 'Saint George',
		'05': 'Saint John',
		'06': 'Saint Joseph',
		'07': 'Saint Luke',
		'08': 'Saint Mark',
		'09': 'Saint Patrick',
		'10': 'Saint Paul',
		'11': 'Saint Peter',
	},
	DO: {
		'02': 'Azua',
		'03': 'Bahoruco',
		'04': 'Barahona',
		'05': 'Dajabón',
		'01': 'Distrito Nacional (Santo Domingo)',
		'06': 'Duarte',
		'08': 'El Seybo [El Seibo]',
		'09': 'Espaillat',
		'30': 'Hato Mayor',
		'10': 'Independencia',
		'11': 'La Altagracia',
		'07': 'La Estrelleta [Elías Piña]',
		'12': 'La Romana',
		'13': 'La Vega',
		'14': 'María Trinidad Sánchez',
		'28': 'Monseñor Nouel',
		'15': 'Monte Cristi',
		'29': 'Monte Plata',
		'16': 'Pedernales',
		'17': 'Peravia',
		'18': 'Puerto Plata',
		'19': 'Salcedo',
		'20': 'Samaná',
		'21': 'San Cristóbal',
		'31': 'San Jose de Ocoa',
		'22': 'San Juan',
		'23': 'San Pedro de Macorís',
		'25': 'Santiago',
		'26': 'Santiago Rodríguez',
		'24': 'Sánchez Ramírez',
		'27': 'Valverde',
	},
	EC: {
		A: 'Azuay',
		B: 'Bolívar',
		C: 'Carchi',
		F: 'Cañar',
		H: 'Chimborazo',
		X: 'Cotopaxi',
		O: 'El Oro',
		E: 'Esmeraldas',
		W: 'Galápagos',
		G: 'Guayas',
		I: 'Imbabura',
		L: 'Loja',
		R: 'Los Ríos',
		M: 'Manabí',
		S: 'Morona-Santiago',
		N: 'Napo',
		D: 'Orellana',
		Y: 'Pastaza',
		P: 'Pichincha',
		'X1~': 'Santa Elena',
		'X2~': 'Santo Domingo de los Tsachilas',
		U: 'Sucumbíos',
		T: 'Tungurahua',
		Z: 'Zamora-Chinchipe',
	},
	EG: {
		DK: 'Ad Daqahliyah',
		BA: 'Al Bahr al Ahmar',
		BH: 'Al Buhayrah',
		FYM: 'Al Fayyum',
		GH: 'Al Gharbiyah',
		ALX: 'Al Iskandariyah',
		IS: 'Al Ismā`īlīyah',
		GZ: 'Al Jizah',
		MNF: 'Al Minufiyah',
		MN: 'Al Minya',
		C: 'Al Qahirah',
		KB: 'Al Qalyubiyah',
		WAD: 'Al Wadi al Jadid',
		SUZ: 'As Suways',
		SHR: 'Ash Sharqiyah',
		ASN: 'Aswan',
		AST: 'Asyut',
		BNS: 'Bani Suwayf',
		PTS: 'Būr Sa`īd',
		DT: 'Dumyat',
		JS: 'Janub Sina\'',
		KFS: 'Kafr ash Shaykh',
		MT: 'Matrūh',
		KN: 'Qina',
		SIN: 'Shamal Sina\'',
		SHG: 'Suhaj',
		LX: 'al-Uqsur',
	},
	SV: {
		AH: 'Ahuachapán',
		CA: 'Cabañas',
		CH: 'Chalatenango',
		CU: 'Cuscatlán',
		LI: 'La Libertad',
		PA: 'La Paz',
		UN: 'La Unión',
		MO: 'Morazán',
		SM: 'San Miguel',
		SS: 'San Salvador',
		SV: 'San Vicente',
		SA: 'Santa Ana',
		SO: 'Sonsonate',
		US: 'Usulután',
	},
	GQ: {
		AN: 'Annobón',
		BN: 'Bioko Norte',
		BS: 'Bioko Sur',
		CS: 'Centro Sur',
		KN: 'Kie-Ntem',
		LI: 'Litoral',
		C: 'Región Continental',
		I: 'Región Insular',
		WN: 'Wele-Nzás',
	},
	ER: {
		AN: 'Anseba',
		DU: 'Debub',
		DK: 'Debubawi Keyih Bahri [Debub-Keih-Bahri]',
		GB: 'Gash-Barka',
		MA: 'Maakel [Maekel]',
		SK: 'Semenawi Keyih Bahri [Semien-Keih-Bahri]',
	},
	EE: {
		'37': 'Harjumaa',
		'39': 'Hiiumaa',
		'44': 'Ida-Virumaa',
		'51': 'Järvamaa',
		'49': 'Jõgevamaa',
		'59': 'Lääne-Virumaa',
		'57': 'Läänemaa',
		'67': 'Pärnumaa',
		'65': 'Põlvamaa',
		'70': 'Raplamaa',
		'74': 'Saaremaa',
		'78': 'Tartumaa',
		'82': 'Valgamaa',
		'84': 'Viljandimaa',
		'86': 'Võrumaa',
	},
	ET: {
		AA: 'Adis Abeba',
		AF: 'Afar',
		AM: 'Amara',
		BE: 'Binshangul Gumuz',
		DD: 'Dire Dawa',
		GA: 'Gambela Hizboch',
		HA: 'Hareri Hizb',
		OR: 'Oromiya',
		SO: 'Sumale',
		TI: 'Tigray',
		SN: 'YeDebub Biheroch Bihereseboch na Hizboch',
	},
	FK: {},
	FO: {},
	FJ: {
		C: 'Central',
		E: 'Eastern',
		N: 'Northern',
		R: 'Rotuma',
		W: 'Western',
	},
	FI: {
		AL: 'Ahvenanmaan lääni',
		ES: 'Etelä-Suomen lääni',
		IS: 'Itä-Suomen lääni',
		LL: 'Lapin lääni',
		LS: 'Länsi-Suomen lääni',
		OL: 'Oulun lääni',
	},
	FR: {
		'01': 'Ain',
		'02': 'Aisne',
		'03': 'Allier',
		'06': 'Alpes-Maritimes',
		'04': 'Alpes-de-Haute-Provence',
		'08': 'Ardennes',
		'07': 'Ardèche',
		'09': 'Ariège',
		'10': 'Aube',
		'11': 'Aude',
		'12': 'Aveyron',
		'67': 'Bas-Rhin',
		'13': 'Bouches-du-Rhône',
		'14': 'Calvados',
		'15': 'Cantal',
		'16': 'Charente',
		'17': 'Charente-Maritime',
		'18': 'Cher',
		'19': 'Corrèze',
		'2A': 'Corse-du-Sud',
		'23': 'Creuse',
		'21': 'Côte-d\'Or',
		'22': 'Côtes-d\'Armor',
		'79': 'Deux-Sèvres',
		'24': 'Dordogne',
		'25': 'Doubs',
		'26': 'Drôme',
		'91': 'Essonne',
		'27': 'Eure',
		'28': 'Eure-et-Loir',
		'29': 'Finistère',
		'30': 'Gard',
		'32': 'Gers',
		'33': 'Gironde',
		'68': 'Haut-Rhin',
		'2B': 'Haute-Corse',
		'31': 'Haute-Garonne',
		'43': 'Haute-Loire',
		'52': 'Haute-Marne',
		'74': 'Haute-Savoie',
		'70': 'Haute-Saône',
		'87': 'Haute-Vienne',
		'05': 'Hautes-Alpes',
		'65': 'Hautes-Pyrénées',
		'92': 'Hauts-de-Seine',
		'34': 'Hérault',
		'35': 'Ille-et-Vilaine',
		'36': 'Indre',
		'37': 'Indre-et-Loire',
		'38': 'Isère',
		'39': 'Jura',
		'40': 'Landes',
		'41': 'Loir-et-Cher',
		'42': 'Loire',
		'44': 'Loire-Atlantique',
		'45': 'Loiret',
		'46': 'Lot',
		'47': 'Lot-et-Garonne',
		'48': 'Lozère',
		'49': 'Maine-et-Loire',
		'50': 'Manche',
		'51': 'Marne',
		'53': 'Mayenne',
		'YT': 'Mayotte (see also separate entry under YT)',
		'54': 'Meurthe-et-Moselle',
		'55': 'Meuse',
		'56': 'Morbihan',
		'57': 'Moselle',
		'58': 'Nièvre',
		'59': 'Nord',
		'NC': 'Nouvelle-Calédonie (see also separate entry under NC)',
		'60': 'Oise',
		'61': 'Orne',
		'75': 'Paris',
		'62': 'Pas-de-Calais',
		'PF': 'Polynésie française (see also separate entry under PF)',
		'63': 'Puy-de-Dôme',
		'64': 'Pyrénées-Atlantiques',
		'66': 'Pyrénées-Orientales',
		'69': 'Rhône',
		'PM': 'Saint-Pierre-et-Miquelon (see also separate entry under PM)',
		'72': 'Sarthe',
		'73': 'Savoie',
		'71': 'Saône-et-Loire',
		'76': 'Seine-Maritime',
		'93': 'Seine-Saint-Denis',
		'77': 'Seine-et-Marne',
		'80': 'Somme',
		'81': 'Tarn',
		'82': 'Tarn-et-Garonne',
		'TF': 'Terres Australes Françaises (see also separate entry under TF)',
		'90': 'Territoire de Belfort',
		'95': 'Val-d\'Oise',
		'94': 'Val-de-Marne',
		'83': 'Var',
		'84': 'Vaucluse',
		'85': 'Vendée',
		'86': 'Vienne',
		'88': 'Vosges',
		'WF': 'Wallis et Futuna (see also separate entry under WF)',
		'89': 'Yonne',
		'78': 'Yvelines',
	},
	GF: {},
	PF: {},
	TF: {
		'X2~': 'Crozet Islands',
		'X1~': 'Ile Saint-Paul et Ile Amsterdam',
		'X4~': 'Iles Eparses',
		'X3~': 'Kerguelen',
	},
	GA: {
		'1': 'Estuaire',
		'2': 'Haut-Ogooué',
		'3': 'Moyen-Ogooué',
		'4': 'Ngounié',
		'5': 'Nyanga',
		'6': 'Ogooué-Ivindo',
		'7': 'Ogooué-Lolo',
		'8': 'Ogooué-Maritime',
		'9': 'Woleu-Ntem',
	},
	GM: {
		B: 'Banjul',
		L: 'Lower River',
		M: 'MacCarthy Island',
		N: 'North Bank',
		U: 'Upper River',
		W: 'Western',
	},
	GE: {
		AB: 'Abkhazia',
		AJ: 'Ajaria',
		GU: 'Guria',
		IM: 'Imereti',
		KA: 'Kakheti',
		KK: 'Kvemo Kartli',
		MM: 'Mtskheta-Mtianeti',
		RL: 'Racha-Lechkhumi [and] Kvemo Svaneti',
		SZ: 'Samegrelo-Zemo Svaneti',
		SJ: 'Samtskhe-Javakheti',
		SK: 'Shida Kartli',
		TB: 'Tbilisi',
	},
	DE: {
		BW: 'Baden-Württemberg',
		BY: 'Bayern',
		BE: 'Berlin',
		BB: 'Brandenburg',
		HB: 'Bremen',
		HH: 'Hamburg',
		HE: 'Hessen',
		MV: 'Mecklenburg-Vorpommern',
		NI: 'Niedersachsen',
		NW: 'Nordrhein-Westfalen',
		RP: 'Rheinland-Pfalz',
		SL: 'Saarland',
		SN: 'Sachsen',
		ST: 'Sachsen-Anhalt',
		SH: 'Schleswig-Holstein',
		TH: 'Thüringen',
	},
	GH: {
		AH: 'Ashanti',
		BA: 'Brong-Ahafo',
		CP: 'Central',
		EP: 'Eastern',
		AA: 'Greater Accra',
		NP: 'Northern',
		UE: 'Upper East',
		UW: 'Upper West',
		TV: 'Volta',
		WP: 'Western',
	},
	GI: {},
	GR: {
		'13': 'Achaïa',
		'69': 'Agio Oros',
		'01': 'Aitolia-Akarnania',
		'11': 'Argolis',
		'12': 'Arkadia',
		'31': 'Arta',
		'A1': 'Attiki',
		'64': 'Chalkidiki',
		'94': 'Chania',
		'85': 'Chios',
		'81': 'Dodekanisos',
		'52': 'Drama',
		'71': 'Evros',
		'05': 'Evrytania',
		'04': 'Evvoia',
		'63': 'Florina',
		'07': 'Fokis',
		'06': 'Fthiotis',
		'51': 'Grevena',
		'14': 'Ileia',
		'53': 'Imathia',
		'33': 'Ioannina',
		'91': 'Irakleion',
		'41': 'Karditsa',
		'56': 'Kastoria',
		'55': 'Kavalla',
		'23': 'Kefallinia',
		'22': 'Kerkyra',
		'57': 'Kilkis',
		'15': 'Korinthia',
		'58': 'Kozani',
		'82': 'Kyklades',
		'16': 'Lakonia',
		'42': 'Larisa',
		'92': 'Lasithion',
		'24': 'Lefkas',
		'83': 'Lesvos',
		'43': 'Magnisia',
		'17': 'Messinia',
		'59': 'Pella',
		'61': 'Pieria',
		'34': 'Preveza',
		'93': 'Rethymnon',
		'73': 'Rodopi',
		'84': 'Samos',
		'62': 'Serrai',
		'32': 'Thesprotia',
		'54': 'Thessaloniki',
		'44': 'Trikala',
		'03': 'Voiotia',
		'72': 'Xanthi',
		'21': 'Zakynthos',
	},
	GL: {},
	GD: {
		'01': 'Saint Andrew',
		'02': 'Saint David',
		'03': 'Saint George',
		'04': 'Saint John',
		'05': 'Saint Mark',
		'06': 'Saint Patrick',
		'10': 'Southern Grenadine Islands',
	},
	GP: {},
	GU: {},
	GT: {
		AV: 'Alta Verapaz',
		BV: 'Baja Verapaz',
		CM: 'Chimaltenango',
		CQ: 'Chiquimula',
		PR: 'El Progreso',
		ES: 'Escuintla',
		GU: 'Guatemala',
		HU: 'Huehuetenango',
		IZ: 'Izabal',
		JA: 'Jalapa',
		JU: 'Jutiapa',
		PE: 'Petén',
		QZ: 'Quetzaltenango',
		QC: 'Quiché',
		RE: 'Retalhuleu',
		SA: 'Sacatepéquez',
		SM: 'San Marcos',
		SR: 'Santa Rosa',
		SO: 'Sololá',
		SU: 'Suchitepéquez',
		TO: 'Totonicapán',
		ZA: 'Zacapa',
	},
	GG: {},
	GN: {
		BE: 'Beyla',
		BF: 'Boffa',
		BK: 'Boké',
		C: 'Conakry',
		CO: 'Coyah',
		DB: 'Dabola',
		DL: 'Dalaba',
		DI: 'Dinguiraye',
		DU: 'Dubréka',
		FA: 'Faranah',
		FO: 'Forécariah',
		FR: 'Fria',
		GA: 'Gaoual',
		GU: 'Guékédou',
		KA: 'Kankan',
		KD: 'Kindia',
		KS: 'Kissidougou',
		KB: 'Koubia',
		KN: 'Koundara',
		KO: 'Kouroussa',
		KE: 'Kérouané',
		LA: 'Labé',
		LO: 'Lola',
		LE: 'Lélouma',
		MC: 'Macenta',
		ML: 'Mali',
		MM: 'Mamou',
		MD: 'Mandiana',
		NZ: 'Nzérékoré',
		PI: 'Pita',
		SI: 'Siguiri',
		TO: 'Tougué',
		TE: 'Télimélé',
		YO: 'Yomou',
	},
	GW: {
		BA: 'Bafatá',
		BM: 'Biombo',
		BS: 'Bissau',
		BL: 'Bolama',
		CA: 'Cacheu',
		GA: 'Gabú',
		OI: 'Oio',
		QU: 'Quinara',
		TO: 'Tombali',
	},
	GY: {
		BA: 'Barima-Waini',
		CU: 'Cuyuni-Mazaruni',
		DE: 'Demerara-Mahaica',
		EB: 'East Berbice-Corentyne',
		ES: 'Essequibo Islands-West Demerara',
		MA: 'Mahaica-Berbice',
		PM: 'Pomeroon-Supenaam',
		PT: 'Potaro-Siparuni',
		UD: 'Upper Demerara-Berbice',
		UT: 'Upper Takutu-Upper Essequibo',
	},
	HT: {
		AR: 'Artibonite',
		CE: 'Centre',
		GA: 'Grande-Anse',
		ND: 'Nord',
		NE: 'Nord-Est',
		NO: 'Nord-Ouest',
		OU: 'Ouest',
		SD: 'Sud',
		SE: 'Sud-Est',
	},
	HM: {},
	VA: {},
	HN: {
		AT: 'Atlántida',
		CH: 'Choluteca',
		CL: 'Colón',
		CM: 'Comayagua',
		CP: 'Copán',
		CR: 'Cortés',
		EP: 'El Paraíso',
		FM: 'Francisco Morazán',
		GD: 'Gracias a Dios',
		IN: 'Intibucá',
		IB: 'Islas de la Bahía',
		LP: 'La Paz',
		LE: 'Lempira',
		OC: 'Ocotepeque',
		OL: 'Olancho',
		SB: 'Santa Bárbara',
		VA: 'Valle',
		YO: 'Yoro',
	},
	HK: {},
	HU: {
		BA: 'Baranya',
		BZ: 'Borsod-Abaúj-Zemplén',
		BU: 'Budapest',
		BK: 'Bács-Kiskun',
		BE: 'Békés',
		BC: 'Békéscsaba',
		CS: 'Csongrád',
		DE: 'Debrecen',
		DU: 'Dunaújváros',
		EG: 'Eger',
		FE: 'Fejér',
		GY: 'Győr',
		GS: 'Győr-Moson-Sopron',
		HB: 'Hajdú-Bihar',
		HE: 'Heves',
		HV: 'Hódmezővásárhely',
		JN: 'Jász-Nagykun-Szolnok',
		KV: 'Kaposvár',
		KM: 'Kecskemét',
		KE: 'Komárom-Esztergom',
		MI: 'Miskolc',
		NK: 'Nagykanizsa',
		NY: 'Nyíregyháza',
		NO: 'Nógrád',
		PE: 'Pest',
		PS: 'Pécs',
		ST: 'Salgótarján',
		SO: 'Somogy',
		SN: 'Sopron',
		SZ: 'Szabolcs-Szatmár-Bereg',
		SD: 'Szeged',
		SS: 'Szekszárd',
		SK: 'Szolnok',
		SH: 'Szombathely',
		SF: 'Székesfehérvár',
		TB: 'Tatabánya',
		TO: 'Tolna',
		VA: 'Vas',
		VE: 'Veszprém',
		VM: 'Veszprém',
		ZA: 'Zala',
		ZE: 'Zalaegerszeg',
		ER: 'Érd',
	},
	IS: {
		'7': 'Austurland',
		'1': 'Höfuðborgarsvæði utan Reykjavíkur',
		'6': 'Norðurland eystra',
		'5': 'Norðurland vestra',
		'0': 'Reykjavík',
		'8': 'Suðurland',
		'2': 'Suðurnes',
		'4': 'Vestfirðir',
		'3': 'Vesturland',
	},
	IN: {
		AN: 'Andaman and Nicobar Islands',
		AP: 'Andhra Pradesh',
		AR: 'Arunachal Pradesh',
		AS: 'Assam',
		BR: 'Bihar',
		CH: 'Chandigarh',
		CT: 'Chhattisgarh',
		DN: 'Dadra and Nagar Haveli',
		DD: 'Daman and Diu',
		DL: 'Delhi',
		GA: 'Goa',
		GJ: 'Gujarat',
		HR: 'Haryana',
		HP: 'Himachal Pradesh',
		JK: 'Jammu and Kashmir',
		JH: 'Jharkhand',
		KA: 'Karnataka',
		KL: 'Kerala',
		LD: 'Lakshadweep',
		MP: 'Madhya Pradesh',
		MH: 'Maharashtra',
		MN: 'Manipur',
		ML: 'Meghalaya',
		MZ: 'Mizoram',
		NL: 'Nagaland',
		OR: 'Orissa',
		PY: 'Pondicherry',
		PB: 'Punjab',
		RJ: 'Rajasthan',
		SK: 'Sikkim',
		TN: 'Tamil Nadu',
		TR: 'Tripura',
		UP: 'Uttar Pradesh',
		UL: 'Uttaranchal',
		WB: 'West Bengal',
	},
	// TODO up to here
	ID: 'Indonesia',
	IR: 'Iran, Islamic Republic Of',
	IQ: 'Iraq',
	IE: 'Ireland',
	IM: 'Isle of Man',
	IL: 'Israel',
	IT: 'Italy',
	JM: 'Jamaica',
	JP: 'Japan',
	JE: 'Jersey',
	JO: 'Jordan',
	KZ: 'Kazakhstan',
	KE: 'Kenya',
	KI: 'Kiribati',
	KP: 'Korea, Democratic People\'s Republic Of',
	KR: 'Korea, Republic of',
	KW: 'Kuwait',
	KG: 'Kyrgyzstan',
	LA: 'Lao People\'s Democratic Republic',
	LV: 'Latvia',
	LB: 'Lebanon',
	LS: 'Lesotho',
	LR: 'Liberia',
	LY: 'Libya',
	LI: 'Liechtenstein',
	LT: 'Lithuania',
	LU: 'Luxembourg',
	MO: 'Macao',
	MK: 'Macedonia, the Former Yugoslav Republic Of',
	MG: 'Madagascar',
	MW: 'Malawi',
	MY: 'Malaysia',
	MV: 'Maldives',
	ML: 'Mali',
	MT: 'Malta',
	MH: 'Marshall Islands',
	MQ: 'Martinique',
	MR: 'Mauritania',
	MU: 'Mauritius',
	YT: 'Mayotte',
	MX: 'Mexico',
	FM: 'Micronesia, Federated States Of',
	MD: 'Moldova, Republic of',
	MC: 'Monaco',
	MN: 'Mongolia',
	ME: 'Montenegro',
	MS: 'Montserrat',
	MA: 'Morocco',
	MZ: 'Mozambique',
	MM: 'Myanmar',
	NA: 'Namibia',
	NR: 'Nauru',
	NP: 'Nepal',
	NL: 'Netherlands',
	AN: 'Netherlands Antilles',
	NC: 'New Caledonia',
	NZ: {
		AUK: 'Auckland',
		BOP: 'Bay of Plenty',
		CAN: 'Canterbury',
		'X1~': 'Chatham  Islands',
		GIS: 'Gisborne',
		HKB: 'Hawkess Bay',
		MWT: 'Manawatu-Wanganui',
		MBH: 'Marlborough',
		NSN: 'Nelson',
		NTL: 'Northland',
		OTA: 'Otago',
		STL: 'Southland',
		TKI: 'Taranaki',
		TAS: 'Tasman',
		WKO: 'Waikato',
		WGN: 'Wellington',
		WTC: 'West Coast',
	},
	NI: 'Nicaragua',
	NE: 'Niger',
	NG: 'Nigeria',
	NU: 'Niue',
	NF: 'Norfolk Island',
	MP: 'Northern Mariana Islands',
	NO: 'Norway',
	OM: 'Oman',
	PK: 'Pakistan',
	PW: 'Palau',
	PS: 'Palestine, State of',
	PA: 'Panama',
	PG: 'Papua New Guinea',
	PY: 'Paraguay',
	PE: 'Peru',
	PH: 'Philippines',
	PN: 'Pitcairn',
	PL: 'Poland',
	PT: 'Portugal',
	PR: 'Puerto Rico',
	QA: 'Qatar',
	RO: 'Romania',
	RU: 'Russian Federation',
	RW: 'Rwanda',
	RE: 'Réunion',
	BL: 'Saint Barthélemy',
	SH: 'Saint Helena',
	KN: 'Saint Kitts And Nevis',
	LC: 'Saint Lucia',
	MF: 'Saint Martin',
	PM: 'Saint Pierre And Miquelon',
	VC: 'Saint Vincent And The Grenedines',
	WS: 'Samoa',
	SM: 'San Marino',
	ST: 'Sao Tome and Principe',
	SA: 'Saudi Arabia',
	SN: 'Senegal',
	RS: 'Serbia',
	SC: 'Seychelles',
	SL: 'Sierra Leone',
	SG: {
		'X1~': 'Singapore - No State',
	},
	SX: 'Sint Maarten',
	SK: 'Slovakia',
	SI: 'Slovenia',
	SB: 'Solomon Islands',
	SO: 'Somalia',
	ZA: {
		EC: 'Eastern Cape',
		FS: 'Free State',
		GT: 'Gauteng',
		NL: 'Kwazulu-Natal',
		LP: 'Limpopo',
		MP: 'Mpumalanga',
		NW: 'North-West',
		NC: 'Northern Cape',
		WC: 'Western Cape',
	},
	GS: 'South Georgia and the South Sandwich Islands',
	SS: 'South Sudan',
	ES: 'Spain',
	LK: 'Sri Lanka',
	SD: 'Sudan',
	SR: 'Suriname',
	SJ: 'Svalbard And Jan Mayen',
	SZ: 'Swaziland',
	SE: 'Sweden',
	CH: 'Switzerland',
	SY: 'Syrian Arab Republic',
	TW: 'Taiwan, Republic Of China',
	TJ: 'Tajikistan',
	TZ: 'Tanzania, United Republic of',
	TH: 'Thailand',
	TL: 'Timor-Leste',
	TG: 'Togo',
	TK: 'Tokelau',
	TO: 'Tonga',
	TT: 'Trinidad and Tobago',
	TN: 'Tunisia',
	TR: 'Turkey',
	TM: 'Turkmenistan',
	TC: 'Turks and Caicos Islands',
	TV: 'Tuvalu',
	UG: 'Uganda',
	UA: 'Ukraine',
	AE: 'United Arab Emirates',
	GB: {
		ABE: 'Aberdeen City',
		ABD: 'Aberdeenshire',
		ANS: 'Angus',
		ANT: 'Antrim',
		ARD: 'Ards',
		AGB: 'Argyll and Bute',
		ARM: 'Armagh',
		BLA: 'Ballymena',
		BLY: 'Ballymoney',
		BNB: 'Banbridge',
		BDG: 'Barking and Dagenham',
		BNE: 'Barnet',
		BNS: 'Barnsley',
		BAS: 'Bath and North East Somerset',
		BDF: 'Bedfordshire',
		BFS: 'Belfast',
		BEX: 'Bexley',
		BIR: 'Birmingham',
		BBD: 'Blackburn with Darwen',
		BPL: 'Blackpool',
		BGW: 'Blaenau Gwent',
		BOL: 'Bolton',
		BMH: 'Bournemouth',
		BRC: 'Bracknell Forest',
		BRD: 'Bradford',
		BEN: 'Brent',
		BGE: 'Bridgend [Pen-y-bont ar Ogwr GB-POG]',
		BNH: 'Brighton and Hove',
		BST: 'Bristol City of',
		BRY: 'Bromley',
		BKM: 'Buckinghamshire',
		BUR: 'Bury',
		CAY: 'Caerphilly [Caerffili GB-CAF]',
		CLD: 'Calderdale',
		CAM: 'Cambridgeshire',
		CMD: 'Camden',
		CRF: 'Cardiff [Caerdydd GB-CRD]',
		CMN: 'Carmarthenshire [Sir Gaerfyrddin GB-GFY]',
		CKF: 'Carrickfergus',
		CSR: 'Castlereagh',
		CGN: 'Ceredigion [Sir Ceredigion]',
		CHS: 'Cheshire',
		CLK: 'Clackmannanshire',
		CLR: 'Coleraine',
		CWY: 'Conwy',
		CKT: 'Cookstown',
		CON: 'Cornwall',
		COV: 'Coventry',
		CGV: 'Craigavon',
		CRY: 'Croydon',
		CMA: 'Cumbria',
		DAL: 'Darlington',
		DEN: 'Denbighshire [Sir Ddinbych GB-DDB]',
		DER: 'Derby',
		DBY: 'Derbyshire',
		DRY: 'Derry',
		DEV: 'Devon',
		DNC: 'Doncaster',
		DOR: 'Dorset',
		DOW: 'Down',
		DUD: 'Dudley',
		DGY: 'Dumfries and Galloway',
		DND: 'Dundee City',
		DGN: 'Dungannon',
		DUR: 'Durham',
		EAL: 'Ealing',
		EAY: 'East Ayrshire',
		EDU: 'East Dunbartonshire',
		ELN: 'East Lothian',
		ERW: 'East Renfrewshire',
		ERY: 'East Riding of Yorkshire',
		ESX: 'East Sussex',
		EDH: 'Edinburgh City of',
		ELS: 'Eilean Siar',
		ENF: 'Enfield',
		ESS: 'Essex',
		FAL: 'Falkirk',
		FER: 'Fermanagh',
		FIF: 'Fife',
		FLN: 'Flintshire [Sir y Fflint GB-FFL]',
		GAT: 'Gateshead',
		GLG: 'Glasgow City',
		GLS: 'Gloucestershire',
		GRE: 'Greenwich',
		GWN: 'Gwynedd',
		HCK: 'Hackney',
		HAL: 'Halton',
		HMF: 'Hammersmith and Fulham',
		HAM: 'Hampshire',
		HRY: 'Haringey',
		HRW: 'Harrow',
		HPL: 'Hartlepool',
		HAV: 'Havering',
		HEF: 'Herefordshire County of',
		HRT: 'Hertfordshire',
		HLD: 'Highland',
		HIL: 'Hillingdon',
		HNS: 'Hounslow',
		IVC: 'Inverclyde',
		AGY: 'Isle of Anglesey [Sir Ynys Môn GB-YNM]',
		IOW: 'Isle of Wight',
		IOS: 'Isles of Scilly',
		ISL: 'Islington',
		KEC: 'Kensington and Chelsea',
		KEN: 'Kent',
		KHL: 'Kingston upon Hull City of',
		KTT: 'Kingston upon Thames',
		KIR: 'Kirklees',
		KWL: 'Knowsley',
		LBH: 'Lambeth',
		LAN: 'Lancashire',
		LRN: 'Larne',
		LDS: 'Leeds',
		LCE: 'Leicester',
		LEC: 'Leicestershire',
		LEW: 'Lewisham',
		LMV: 'Limavady',
		LIN: 'Lincolnshire',
		LSB: 'Lisburn',
		LIV: 'Liverpool',
		LND: 'London City of',
		LUT: 'Luton',
		MFT: 'Magherafelt',
		MAN: 'Manchester',
		MDW: 'Medway',
		MTY: 'Merthyr Tydfil [Merthyr Tudful GB-MTU]',
		MRT: 'Merton',
		MDB: 'Middlesbrough',
		MLN: 'Midlothian',
		MIK: 'Milton Keynes',
		MON: 'Monmouthshire [Sir Fynwy GB-FYN]',
		MRY: 'Moray',
		MYL: 'Moyle',
		NTL: 'Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]',
		NET: 'Newcastle upon Tyne',
		NWM: 'Newham',
		NWP: 'Newport [Casnewydd GB-CNW]',
		NYM: 'Newry and Mourne',
		NTA: 'Newtownabbey',
		NFK: 'Norfolk',
		NAY: 'North Ayrshire',
		NDN: 'North Down',
		NEL: 'North East Lincolnshire',
		NLK: 'North Lanarkshire',
		NLN: 'North Lincolnshire',
		NSM: 'North Somerset',
		NTY: 'North Tyneside',
		NYK: 'North Yorkshire',
		NTH: 'Northamptonshire',
		NBL: 'Northumberland',
		NGM: 'Nottingham',
		NTT: 'Nottinghamshire',
		OLD: 'Oldham',
		OMH: 'Omagh',
		ORK: 'Orkney Islands',
		OXF: 'Oxfordshire',
		PEM: 'Pembrokeshire [Sir Benfro GB-BNF]',
		PKN: 'Perth and Kinross',
		PTE: 'Peterborough',
		PLY: 'Plymouth',
		POL: 'Poole',
		POR: 'Portsmouth',
		POW: 'Powys',
		RDG: 'Reading',
		RDB: 'Redbridge',
		RCC: 'Redcar and Cleveland',
		RFW: 'Renfrewshire',
		RCT: 'Rhondda, Cynon Taff [Rhondda Cynon Taf]',
		RIC: 'Richmond upon Thames',
		RCH: 'Rochdale',
		ROT: 'Rotherham',
		RUT: 'Rutland',
		SLF: 'Salford',
		SAW: 'Sandwell',
		SCB: 'Scottish Borders The',
		SFT: 'Sefton',
		SHF: 'Sheffield',
		ZET: 'Shetland Islands',
		SHR: 'Shropshire',
		SLG: 'Slough',
		SOL: 'Solihull',
		SOM: 'Somerset',
		SAY: 'South Ayrshire',
		SGC: 'South Gloucestershire',
		SLK: 'South Lanarkshire',
		STY: 'South Tyneside',
		STH: 'Southampton',
		SOS: 'Southend-on-Sea',
		SWK: 'Southwark',
		SHN: 'St. Helens',
		STS: 'Staffordshire',
		STG: 'Stirling',
		SKP: 'Stockport',
		STT: 'Stockton-on-Tees',
		STE: 'Stoke-on-Trent',
		STB: 'Strabane',
		SFK: 'Suffolk',
		SND: 'Sunderland',
		SRY: 'Surrey',
		STN: 'Sutton',
		SWA: 'Swansea [Abertawe GB-ATA]',
		SWD: 'Swindon',
		TAM: 'Tameside',
		TFW: 'Telford and Wrekin',
		THR: 'Thurrock',
		TOB: 'Torbay',
		TOF: 'Torfaen [Tor-faen]',
		TWH: 'Tower Hamlets',
		TRF: 'Trafford',
		VGL: 'Vale of Glamorgan The [Bro Morgannwg GB-BMG]',
		WKF: 'Wakefield',
		WLL: 'Walsall',
		WFT: 'Waltham Forest',
		WND: 'Wandsworth',
		WRT: 'Warrington',
		WAR: 'Warwickshire',
		WBK: 'West Berkshire',
		WDU: 'West Dunbartonshire',
		WLN: 'West Lothian',
		WSX: 'West Sussex',
		WSM: 'Westminster',
		WGN: 'Wigan',
		WIL: 'Wiltshire',
		WNM: 'Windsor and Maidenhead',
		WRL: 'Wirral',
		WOK: 'Wokingham',
		WLV: 'Wolverhampton',
		WOR: 'Worcestershire',
		WRX: 'Wrexham [Wrecsam GB-WRC]',
		YOR: 'York',
	},
	US: {
		AL: 'Alabama',
		AK: 'Alaska',
		AS: 'American Samoa',
		AZ: 'Arizona',
		AR: 'Arkansas',
		AA: 'Armed Forces Americas',
		AE: 'Armed Forces Europe',
		AP: 'Armed Forces Pacific',
		CA: 'California',
		CO: 'Colorado',
		CT: 'Connecticut',
		DE: 'Delaware',
		DC: 'District of Columbia',
		FL: 'Florida',
		GA: 'Georgia',
		GU: 'Guam',
		HI: 'Hawaii',
		ID: 'Idaho',
		IL: 'Illinois',
		IN: 'Indiana',
		IA: 'Iowa',
		KS: 'Kansas',
		KY: 'Kentucky',
		LA: 'Louisiana',
		ME: 'Maine',
		MD: 'Maryland',
		MA: 'Massachusetts',
		MI: 'Michigan',
		MN: 'Minnesota',
		MS: 'Mississippi',
		MO: 'Missouri',
		MT: 'Montana',
		NE: 'Nebraska',
		NV: 'Nevada',
		NH: 'New Hampshire',
		NJ: 'New Jersey',
		NM: 'New Mexico',
		NY: 'New York',
		NC: 'North Carolina',
		ND: 'North Dakota',
		MP: 'Northern Mariana Islands',
		OH: 'Ohio',
		OK: 'Oklahoma',
		OR: 'Oregon',
		PA: 'Pennsylvania',
		PR: 'Puerto Rico',
		RI: 'Rhode Island',
		SC: 'South Carolina',
		SD: 'South Dakota',
		TN: 'Tennessee',
		TX: 'Texas',
		UM: 'United States Minor Outlying Islands',
		UT: 'Utah',
		VT: 'Vermont',
		VI: 'Virgin Islands U.S.',
		VA: 'Virginia',
		WA: 'Washington',
		WV: 'West Virginia',
		WI: 'Wisconsin',
		WY: 'Wyoming',
	},
	UM: 'United States Minor Outlying Islands',
	UY: 'Uruguay',
	UZ: 'Uzbekistan',
	VU: 'Vanuatu',
	VE: 'Venezuela, Bolivarian Republic of',
	VN: 'Vietnam',
	VG: 'Virgin Islands, British',
	VI: 'Virgin Islands, U.S.',
	WF: 'Wallis and Futuna',
	EH: 'Western Sahara',
	YE: 'Yemen',
	ZM: 'Zambia',
	ZW: 'Zimbabwe',
	AX: {},
};
