<?php
/**
 * A factory for Generic_Post instances
 *
 * @file wp-chargify/includes/libraries/model.php
 * @package WPCHargify
 */

namespace Chargify\Libraries;

/**
 * An actual model instance generated by a `ModelBuilder`.  There are default base wrappers for
 *
 * @author Zachary Scott <zscott@alyte.com.au>
 */
class Model { }
